### ISSUE TITLE
implement test output

### ISSUE THREAD

**Issue by barakplasma** [BCNelson/vscode-tap-harness#2]
would you accept a PR which adds [test-output](https://code.visualstudio.com/api/extension-guides/testing#test-output)?
something like [this](https://github.com/microsoft/vscode-extension-samples/blob/dec963c83a827e819b329fe1ba462906fccc33df/test-provider-sample/src/testTree.ts#L110)

EDIT: reduced my goal to what is supported by TAP

**Comment by BCNelson** [comment]
I would be happy to review a PR that adds that feature.
I'm a little concerned with how it would be implemented as the [spec](https://testanything.org/tap-version-14-specification.html) does not contain any fields that can be used to know the expected output.

**Comment by barakplasma** [comment]
I want to display the failure message next to the test, which [in the spec example can look like the example below](https://testanything.org/tap-version-14-specification.html#:~:text=not%20ok%202%20%2D%20First%20line%20of%20the%20input%20valid%0A%20%20%2D%2D%2D%0A%20%20message%3A%20%27First%20line%20invalid%27%0A%20%20severity%3A%20fail%0A%20%20data%3A%0A%20%20%20%20got%3A%20%27Flirble%27%0A%20%20%20%20expect%3A%20%27Fnible%27) , and usually explains the failure like the diff between actual/expected value

 ```
not ok 2 - First line of the input valid
   ---
   message: 'First line invalid'
   severity: fail
   data:
     got: 'Flirble'
     expect: 'Fnible'
```

BTW, I started using your extension for tests written using [the node:test module which facilitates the creation of JavaScript tests that report results in TAP format](https://nodejs.org/docs/latest-v18.x/api/test.html#:~:text=The%20node%3Atest%20module%20facilitates%20the%20creation%20of%20JavaScript%20tests%20that%20report%20results%20in%20TAP%20format). Really liking the extension so far, so thanks!

**Comment by BCNelson** [comment]
> Currently (March 2022) the data structure represented by a YAML Diagnostic block has not been standardized. TAP14 Harnesses must allow any data structures supported by their YAML parser implementation.
>
>A future version of this specification may provide guidance regarding YAML Diagnostic fields in common usage.

That yaml is not defined by the spec. We would need to detect if the yaml contains a known data format and then we could use it to show more information

**Comment by barakplasma** [comment]
my plan is to display the failure message, not to parse anything.

**Comment by BCNelson** [comment]
@barakplasma What part of of the output will you be pulling the failure messages from?

**Comment by barakplasma** [comment]
maybe I will stringify the diag https://github.com/tapjs/tap-parser/blob/main/test/fixtures/yamlish.tap
![image](https://user-images.githubusercontent.com/62937/214502018-912a9428-3c8f-47b8-91be-7757ebf5a063.png)
I want to test against the examples in tap-parser
